### PR TITLE
Download page update

### PR DESCRIPTION
**Pull request by brandonhaslegs**
0 0 0 0_7800_tryit html

To do:
- [x] stack the download blocks on mobile

### CODE REVIEW

**Review by juliendonck — APPROVED** [review]
Nice work

**Review by juliendonck — CHANGES_REQUESTED** [review]
I wouldn't rename `download.html` to `try-it.html`

**Comment by brandonhaslegs** [comment]
> I wouldn't rename `download.html` to `try-it.html`

Well, Ange would! The only problem I see is that we need to set up a redirect (no idea how to do this) so that all old links redirect to tryit.html.

**Comment by juliendonck** [comment]
> > I wouldn't rename `download.html` to `try-it.html`
> 
> Well, Ange would! The only problem I see is that we need to set up a redirect (no idea how to do this) so that all old links redirect to tryit.html.

Ange only spoke about the ui text from what I understood.

**Comment by brandonhaslegs** [comment]
> > > I wouldn't rename `download.html` to `try-it.html`
> > 
> > 
> > Well, Ange would! The only problem I see is that we need to set up a redirect (no idea how to do this) so that all old links redirect to tryit.html.
> 
> Ange only spoke about the ui text from what I understood.

Here's the list she sent me


• Instead of "Try the Beta" at the top, should it be something like "Try Radicle" or "Access Radicle" or "Radicle Access." I think "Access Radicle" is my favorite but happy to discuss.
1. Just want to confirm that the two "here"s in the Etherscan blurb are linked appropriately?
2. In the "Desktop" square, change "Check out our guide to getting started" to "Check out *the* guide to getting started"
3. Under ethBuild change "...call a function on an Ethereum contract by sending it..." to "...call a function on an Ethereum contract (like those to register Radicle names and to create Radicle orgs) by sending it..."
4.  Under MEW change "...interact with smart contracts..." to "...interact with [Radicle] smart contracts..."
5.  Also, would the actual URL be changed to radicle.xyz/tryradicle (or accessradicle, etc)?

I chose "tryit" because that's what the link in the header says too.

**Review by juliendonck — APPROVED** [review]

**Pull request merged**
