### PR TITLE
Linked the community block to the community page

### LINKED ISSUE #246: Link the community block to the community page
image

Text should change from "Join our community or chat with us" to just "[Hang out with us](https://radicle.xyz/community.html)"

### PR DESCRIPTION
**Pull request by soham4abc**
Fixes #246

### CODE REVIEW

**Review by brandonhaslegs — APPROVED** [review]

**Comment by brandonhaslegs** [comment]
Thanks for the contribution @soham4abc!

We require contributors to sign-off (git commit -s) on our DCO for licensing reasons. Could you please do that and force-push the commit after?

**Comment by soham4abc** [comment]
> Thanks for the contribution @soham4abc!
> 
> We require contributors to sign-off (git commit -s) for security reasons. Could you please do that and force-push the commit after?

Done as per request! Thank you!!

**Review by brandonhaslegs — DISMISSED** [review]

**Comment by brandonhaslegs** [comment]
Thanks! I can't merge it just yet … bit complicated, sorry. You'll need to actually go through this process [here](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits).

**Comment by soham4abc** [comment]
> Thanks! I can't merge it just yet … bit complicated, sorry. You'll need to actually go through this process [here](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits).

Hope now it is okay! If anything else is required feel free to request changes!

**Review by brandonhaslegs — APPROVED** [review]

**Pull request merged**
