### PR TITLE
Add Community page

### LINKED ISSUE #236: Add a Community page
Since we have many places where our community exists, I thought we could add a page to the website that serves as a sort of general-purpose place to understand what we use each place for.

This page would link to these places:
- [Discourse](radicle.community)
- [Discord](https://discord.gg/xEGT4vdH)
- [Matrix](matrix.radicle.community)
- [Twitter](twitter.com/radicle)
- [Telegram](telegram.me/radicleworld)
- [Telegram (Thailand)](https://t.me/radicleThailand)

Start of the Figma design [here](https://www.figma.com/file/mM35Q1jG2cADW5ZWYyBIMb/Radicle-Website?node-id=1861%3A84705).

image

### PR DESCRIPTION
**Pull request by brandonhaslegs**
Added all our various online presences.

closes #236

image

### CODE REVIEW

**Comment by brandonhaslegs** [comment]
@juliendonck Not sure how to make the **Community** nav item have an underline when you're on that page.

**Comment by brandonhaslegs** [comment]
@abbey-titcomb Just wrote a bunch of text myself. Feel free to change anything.

**Comment by juliendonck** [comment]
> @juliendonck Not sure how to make the **Community** nav item have an underline when you're on that page.

You have to create a custom header for that page with an active class. https://github.com/radicle-dev/radicle.xyz/pull/237/commits/adf7c50ce1a989f738c947e29b6eacf331230fa7

**Review by juliendonck — APPROVED** [review]
Looks cute

**Comment by abbey-titcomb** [comment]
Pushed a couple copy edits + fixes! Lmk what you think @brandonhaslegs

**Review by abbey-titcomb — APPROVED** [review]

**Review by juliendonck — APPROVED** [review]

**Pull request merged**
