### PR TITLE
Updated feature gifs

### PR DESCRIPTION
**Pull request by cloudhead**

### CODE REVIEW

**Comment by brandonhaslegs** [comment]
I think having one pixel art gif is okay, or all pixel art gifs would also be okay, but having two that are pixel art, and two that are two other styles is weird. Either all different styles, or all the same style, know what I mean?

I like the Local First gif more than the peer-to-peer gif, so maybe we could find another peer-to-peer gif?

**Comment by juliendonck** [comment]
> I think having one pixel art gif is okay, or all pixel art gifs would also be okay, but having two that are pixel art, and two that are two other styles is weird. Either all different styles, or all the same style, know what I mean?
> 
> I like the Local First gif more than the peer-to-peer gif, so maybe we could find another peer-to-peer gif?

This is exactly how I felt.

**Comment by cloudhead** [comment]
Agreed, ok will find another one for p2p, otherwise we can keep the pirate flag.

**Comment by abbey-titcomb** [comment]
fwiw i really don't like the "for the collective" one, it also takes over that entire section. i think we should just stick to the purple heart which is more of an accent

**Comment by brandonhaslegs** [comment]
The pirate flag was cool!

**Comment by juliendonck** [comment]
Yes to pirate flag. I don't mind the collective one. It's like a DMT trip vibe which makes sense in this "collective"-context.

**Comment by abbey-titcomb** [comment]
I get it the vibe that it's going for, but I just don't think it matchs up with the features... The heart resonated bc it can resemble a "like" or a "supporter".

**Comment by cloudhead** [comment]
Ok I brought back the flag and heart. It might make sense though to swap the colors of the P2P section with the Secure by Design, because the pink hand can match up with the pink that way :ok_hand:

**Review by juliendonck — APPROVED** [review]

**Pull request merged**
