### PR TITLE
Deploy to production bucket

### PR DESCRIPTION
**Pull request by xla**
Switch to the bucket we going to use for the production hosting.

### CODE REVIEW

**Comment by jkarni** [comment]
Does this mean the canonical url will be `www.radicle.xyz` (and not `radicle.xyz`)?

**Comment by xla** [comment]
@jkarni That is correct. We can change that but it would require more infrastructure.

**Comment by jkarni** [comment]
How long would that take? We reference `radicle.xyz` in quite a few places.

**Comment by xla** [comment]
@jkarni We can redirect for now and figure out a strategy after.

**Pull request merged**
