### PR TITLE
Blog fixes

### PR DESCRIPTION
**Pull request by juliendonck**

### CODE REVIEW

**Comment by brandonhaslegs** [comment]
So we just need to change the references to the favicon in the head now to reference this new favicon placement.

**Comment by abbey-titcomb** [comment]
"To accomplish both objectives there has always been one prerequisite: make Radicle self-sustainable. 
"
to

""To accomplish both objectives there has always been one prerequisite: <strong>make Radicle self-sustainable.</strong>
"

**Comment by abbey-titcomb** [comment]
"In this reality, building Radicle within the traditional paradigm, as for example a SaaS or open-core company, would force users to remain in a customer/corporation relationship, leaving them vulnerable to eventual extraction. Additionally, if Radicle is to be resilient collaboration infrastructure that truly respects user freedoms, it needs to be developed with trust-minimization in mind, be accessible to anyone in the world, all while remaining adaptive and competitive in a market with well-funded mega-corporations. The only way out of this pattern is to build free and open source networks that are self-sustaining and community owned."

to 

In this reality, building Radicle within the traditional paradigm, as for example a SaaS or open-core company, would force users to remain in a customer/corporation relationship, leaving them vulnerable to eventual extraction. Additionally, if Radicle is to be resilient collaboration infrastructure that truly respects user freedoms, it needs to be developed with trust-minimization in mind, be accessible to anyone in the world, all while remaining adaptive and competitive in a market with well-funded mega-corporations. <strong>The only way out of this pattern is to build free and open source networks that are self-sustaining and community owned</strong>."

**Comment by abbey-titcomb** [comment]
"Operating by these constraints, the token-based sustainability models of today are the most promising path forward for self-sustenance of the Radicle network. More specifically, it’s the emergence of governance primitives within crypto-networks that present a new design space for engineering community-owned open-source protocols & networks. These primitives provide a foundation for a truly "open" open-source world, not one bound by arbitrary walls or delegated sanction rulings."

to

"Operating by these constraints, Radicle recognizes token-based sustainability models as the most promising path forward. More specifically, it’s the emergence of governance primitives within crypto-networks that present a new design space for engineering community-owned open-source protocols & networks. These primitives provide a foundation for a truly "open" open-source world, not one bound by arbitrary walls or delegated sanction rulings."

**Pull request merged**
