### PR TITLE
🎨 Add brand page

### PR DESCRIPTION
**Pull request by brandonhaslegs**
This adds a resource for anyone to download radicle logos and brand assets.

Took care of a few other things here:
- renamed "download" classes to "tryit"
- repurposed the cards structure on the Try It page, so I renamed the blocks from "download" to a generic "block" and "card"

To do:
- [x] why are the buttons now gone on the **Try it** page?
- [x] fix mobile
- [x] hover states for download buttons
- [x] add downloadable assets
- [x] add icons in the download buttons
- [x] add fun gifs
- [x] more fun styling stuff!
- [x] add hidden link to Twitter thread of story behind Radicle brand

image

Signed-off-by: Brandon Oxendine <brandon.oxendine@gmail.com>

### CODE REVIEW

**Comment by rudolfs** [comment]
Is there a link to the brand page anywhere else on the website?

https://radicle.foundation/ isn't working for me, but that's probably a problem on their end.

And the discord invite link is broken:

Screenshot 2022-01-06 at 09 40 50

**Comment by brandonhaslegs** [comment]
So this link is broken? https://discord.com/channels/841318878125490186/843873418205331506

When I click it it takes me to the Discord channel…

**Comment by brandonhaslegs** [comment]
> Is there a link to the brand page anywhere else on the website?

Not yet. I thought it would be fine to just link people to it, but I'll put it in the footer.

**Comment by rudolfs** [comment]
> So this link is broken? https://discord.com/channels/841318878125490186/843873418205331506
> 
> When I click it it takes me to the Discord channel…

No. This one 👉  https://discord.gg/fuG7XeqU

**Review by rudolfs — DISMISSED** [review]
LGTM

**Comment by juliendonck** [comment]
It's great. The only thing is I'm wondering if we can get rid of this gradient banding:

Screenshot 2022-01-06 at 07 58 44

**Comment by brandonhaslegs** [comment]
Yeah sounds good I'll try something else. I don't think we can avoid banding when the gradient is so long. I already am using a "smoothed" gradient generated by some Figma plugin.

**Review by juliendonck — APPROVED** [review]

**Review by juliendonck — APPROVED** [review]

**Pull request merged**
