### PR TITLE
unified place to update the latest upstream version

### PR DESCRIPTION
**Pull request by NunoAlexandre**
Currently, when releasing a new version of the Upstream, updating the link to the macOS and Linux images provided at `radicle.xyz` is one of the steps we undergo.

At the moment, this step is more error-prone than what we would like it to be since we need to update the Upstream's _latest version_ in two places in the [downloads](https://github.com/radicle-dev/radicle.xyz/pull/211/files#diff-357908b71776a63acee9ad4cd874253509c83df8f9799e32256432b4b7f61395) template file.

To make this sub-step less error-prone, we dry the latest upstream version value to a separate file and import it where applicable. This way, we reduce the number of places where changes are needed into a single one.

Together with this pull-request, we update and explain in better detail how to perform this sub-step in this repository in the release docs in the `radicle-upstream`: https://github.com/radicle-dev/radicle-upstream/pull/1641

### CODE REVIEW

**Comment by juliendonck** [comment]
@NunoAlexandre You feel this is clearer? Is this gonna get automated then? Are we also adding this in the docs? I'm curious if this is an improvement. It's def DRY, but not sure if it's better

**Comment by NunoAlexandre** [comment]
> @NunoAlexandre You feel this is clearer? Is this gonna get automated then? Are we also adding this in the docs? I'm curious if this is an improvement. It's def DRY, but not sure if it's better

For context, this was something that I and Rudolfs agreed on improving when I was taught how to release Upstream.

Could you explain how you mean by "clearer"? As in, importing _partials_ is how we separate self-contained elements here. So having the value of the latest version dried doesn't seem - to me - to introduce any unclarity whilst drying things up, which reduces error-proneness.

Let me put it differently: say this PR was introducing the opposite diff - would you find that to be an improvement, duplicating?

> Is this gonna get automated then?

It's automated by running `make` here and it's going to be detailed in the release process.

> Are we also adding this in the docs?

Which _docs_ are you referring to? :)

**Comment by rudolfs** [comment]
Could we automate this even further by pulling the version from http://releases.radicle.xyz/latest.json on deploy?

**Comment by rudolfs** [comment]
You could simplify this even further by moving the website update step to the very end of the release procedure (after the `./scripts/set-latest-release.ts` step) and extending the `Makefile` to pull the latest Upstream version from http://releases.radicle.xyz/latest.json.

This way you could get rid of this step:
```
- [ ] update the latest version in \`partials/upstream-version.mustache\`
```

**Review by rudolfs — APPROVED** [review]

**Comment by juliendonck** [comment]
> You could simplify this even further by moving the website update step to the very end of the release procedure (after the `./scripts/set-latest-release.ts` step) and extending the `Makefile` to pull the latest Upstream version from http://releases.radicle.xyz/latest.json.
> 
> This way you could get rid of this step:
> 
> ```
> - [ ] update the latest version in \`partials/upstream-version.mustache\`
> ```

I find this much more useful then moving the version number into it's own partial. Moving it out of the file where it's twice to me is actually worse then having to replace it twice in one place. I feel it makes it more opaque, imo. But if because of that we can automate it, that would make a lot more sense.

**Comment by NunoAlexandre** [comment]
@juliendonck @rudolfs 

Although I like the idea that Rudolfs posted above to fetch the version from `releases.radicle.xyz`, having that as the mechanism to automate bumping this value introduces more complexity than we need. Namely, 

- it would involve an HTTP request, which _can_ fail and _should_ be handled; 
- it would require extracting a JSON field value from the response we'd get, `version`, which is non-trivial in bash and would involve using `python` or `jq` (see [0]), which - in turn - would represent another requirement to release the app.

Instead, I have pushed a simpler suggestion to the release docs in `Upstream` to simply run the following (automated) command in this repo:

```  bash
echo -n <version> > partials/upstream-version.sh && make
```

Without the small change proposed in this PR, we would not be able to do this. Regarding it making it more 'opaque', note that, indeed, we compromise on that in favour or reusability and ease of updating, both priority factors to seek in a template file. 

[0]: https://stackoverflow.com/questions/1955505/parsing-json-with-unix-tools

**Review by geigerzaehler — APPROVED** [review]
LGTM but I defer to @juliendonck on a final decision.

**Review by juliendonck — APPROVED** [review]

**Pull request merged**
