### PR TITLE
update discord link

### PR DESCRIPTION
**Pull request by PuneetDabral**

### CODE REVIEW

**Comment by PuneetDabral** [comment]
sir please check and merge it...

**Review by brandonhaslegs — APPROVED** [review]

**Review by brandonhaslegs — CHANGES_REQUESTED** [review]
You need to run `make`

**Comment by PuneetDabral** [comment]
can you please explain me

**Comment by SNikhill** [comment]
> can you please explain me

@PuneetDabral 
[This section](https://github.com/radicle-dev/radicle.xyz#dependencies) would be useful in providing you with an answer.

**Comment by PuneetDabral** [comment]
already run this sir

**Comment by brandonhaslegs** [comment]
Running `make` should leave you with a new community.html page too.

**Comment by PuneetDabral** [comment]
ohk

**Pull request closed without merging**
